### ISSUE TITLE
USBInject issue

### ISSUE THREAD

**Issue by azampatti** [randyzhong/OS-X-HP-EliteDesk-800-G2-DM-Clover#1]
Hey, first of all, thanks for this!

I got a G2 mini yesterday, and I stumbled upon this repository with shaved several minutes/hours from my ramp up time! :)

One thing I faced at least during the installation, is that I couldn't get to the setup screen and It was hanging on setting up USB ports. Removed the USBPorts kext and that got me up-n-running. Not sure if you faced the same issue. 

Also, I had to inyect intel from the bootloader with 0x19120000 to get some graphical after the setup.  After a few wiggling I got a full system running now!

Not sure how advanced you are (probably much more than I am) but I can definitely share my config.plist if needed.

Thanks again!
-Aldo

**Comment by randyzhong** [comment]
Hi Aldo,
Thanks for sharing your experience. USBPort.kext is based on my system, you probably need to build your own if faces issues with mine.

By using WEG, Intel® HD Graphics 530 should be supported w/o injecting in the bootloader.
Anyway, it's always welcome to share your config.plist. You can send me an email or upload somewhere like pastebin.

**Comment by tylandercasper** [comment]
I also had an issue with the screen going black during setup, so I added these fixes. It turns out it was an issue with one of the display ports being on a 4k TV. Switching it to the other go it through the setup without any issues. (And I was even able to switch it back afterwards!) So, while I can't confirm these fixes help, I can certainly confirm they don't hurt.

**Comment by randyzhong** [comment]
Please try the v20201115 update. 4K on DP is working.
All USB2.0/3.0/USB-C ports are working.
